# Generated by Django 2.2.5 on 2020-08-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmodel',
            name='dob_id_section',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='fixed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='name_section',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
