# Generated by Django 2.2.5 on 2020-08-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=5),
        ),
    ]
